# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from __future__ import annotations

from textwrap import dedent
from typing import TYPE_CHECKING

from protoc_gen_py import _generate, _Options

from tests.conftest import Plugin

if TYPE_CHECKING:
    from tests.conftest import Protoc


# We test protoc-gen-py within the protobuf plugin's unit test to reuse test harnesses.
# In the future, if we provide a public protoc plugin testing API, we can use it to
# move these to protoc-gen-py itself.


class TestOptions:
    def test_init_files_default(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {"foo/bar/baz.proto": 'syntax = "proto3"; package foo.bar;'},
        )
        assert resp.error == ""
        file_names = {f.name for f in resp.file}
        assert "foo/bar/baz_pb.py" in file_names
        assert "__init__.py" in file_names
        assert "foo/__init__.py" in file_names
        assert "foo/bar/__init__.py" in file_names

    def test_init_files_off_suppresses(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {"foo/bar/baz.proto": 'syntax = "proto3"; package foo.bar;'},
            parameter="init_files=false",
        )
        assert resp.error == ""
        file_names = {f.name for f in resp.file}
        assert "foo/bar/baz_pb.py" in file_names
        assert "__init__.py" not in file_names
        assert "foo/__init__.py" not in file_names
        assert "foo/bar/__init__.py" not in file_names

    def test_escaped_module_self_reference(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {"a-b.proto": 'syntax = "proto3"; package foo; message Foo { Foo f = 1; }'},
            parameter="escape_module_with_hash",
        )
        assert resp.error == ""
        files = {f.name: f.content for f in resp.file}
        assert (
            files["a_b_d44362d6_pb.py"]
            == dedent(
                r'''
            # Generated from a-b.proto. DO NOT EDIT.
            # Generated by protoc-gen-test v1.0.0 with parameter "escape_module_with_hash".
            # ruff: noqa: PGH004
            # ruff: noqa
            # fmt: off

            from __future__ import annotations

            from typing import Literal, TYPE_CHECKING, TypeAlias

            from protobuf import Message
            from protobuf._codegen import file_desc

            if TYPE_CHECKING:
                from protobuf import DescFile


            _FooFields: TypeAlias = Literal["f"]

            class Foo(Message[_FooFields]):
                """
                ```proto
                message foo.Foo
                ```

                Attributes:
                    f:
                        ```proto
                        optional foo.Foo f = 1;
                        ```
                """

                __slots__ = ("f",)

                if TYPE_CHECKING:

                    def __init__(
                        self,
                        *,
                        f: Foo | None = None,
                    ) -> None:
                        pass

                    f: Foo | None


            _DESC = file_desc(
                b'\n\ta-b.proto\x12\x03foo"\x1d\n\x03Foo\x12\x16\n\x01f\x18\x01 \x01(\x0b2\x08.foo.FooR\x01fb\x06proto3',
                [],
                {
                    "Foo": Foo,
                },
            )


            def desc() -> DescFile:
                """Returns the descriptor for the file `a-b.proto`."""
                return _DESC
            '''
            ).lstrip()
        )
