# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Functionality specifically for code generated by protoc-gen-py.

This module may change without following semver, and is not safe to consume directly.
"""

from __future__ import annotations

__all__ = ["Message", "boot", "file_desc", "unset"]

from ._boot import Message, boot, unset
from ._file import file_desc
