name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }} / ${{ matrix.native-ext && 'ext' || 'standard' }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, MacOS, Windows]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
        native-ext: [true, false]
    env:
      # When bumping, also bump top-level env in release.yaml
      MATURIN_ARGS: ${{ (matrix.python-version == '3.10' || matrix.python-version == '3.11') && '--features pyo3/abi3-py310' || '' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "0.11.28"
          python-version: ${{ matrix.python-version }}
      - name: Setup rust
        if: matrix.native-ext
        run: rustup update
      - run: uv sync --locked
      - name: lint protobuf-py-ext
        if: matrix.native-ext
        run: uv run poe ext-lint
      - name: build protobuf-py-ext
        if: matrix.native-ext
        run: uv run poe ext-build
      - run: uv run poe test
        env:
          ASSERT_MARSHALER_IMPLEMENTATION: ${{ matrix.native-ext && 'native' || 'python' }}

  test-pypy:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        # PyPy seems to have possible flaky hangs on Windows related to subprocess invocation
        # which many of our tests use. We go ahead and skip Windows for now.
        os: [Ubuntu, MacOS]
        python-version:
          - "pypy3.11"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "0.11.28"
          python-version: ${{ matrix.python-version }}
      - run: uv sync --locked
      - run: uv run poe test
        env:
          ASSERT_MARSHALER_IMPLEMENTATION: python

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "0.11.28"
          python-version: "3.10"
      - run: uv sync --locked
      - run: uv run poe lint
      - run: uv run poe format
      - run: uv run poe generate
      - run: uv run poe bootstrap
      - run: uv run poe diffcheck
