name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/release.yaml

permissions:
  id-token: write
  attestations: write
  contents: write

env:
  # When bumping, also bump MATURIN_ARGS in ci.yaml
  # maturin flags to build targets we publish non-abi3 wheels for
  UNSTABLE_API_FLAGS: -i 3.12 -i 3.13 -i 3.14 -i 3.14t
  # maturin flags to build targets we publish abi3 wheels for
  ABI3_FLAGS: -i 3.10 --features pyo3/abi3-py310

jobs:
  ext-linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64
          - runner: ubuntu-24.04-arm
            target: aarch64
        manylinux:
          - auto
          - musllinux_1_2
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.x

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Build wheels
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out ../../dist ${{ env.UNSTABLE_API_FLAGS }}
          sccache: true
          manylinux: ${{ matrix.manylinux }}
          working-directory: packages/protobuf-py-ext

      - name: Build abi3 wheels
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out ../../dist ${{ env.ABI3_FLAGS }}
          sccache: true
          manylinux: ${{ matrix.manylinux }}
          working-directory: packages/protobuf-py-ext

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-linux-${{ matrix.platform.target }}-${{ matrix.manylinux }}
          path: dist

  # We only publish abi3 wheels for Windows
  ext-windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-2025
            target: x86_64
          - runner: windows-11-arm
            target: aarch64
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Build abi3 wheels
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          args: --release --out ../../dist ${{ env.ABI3_FLAGS }} --features pyo3/generate-import-lib
          sccache: true
          working-directory: packages/protobuf-py-ext

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: dist

  ext-macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-15
            target: aarch64
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13
            3.14
            3.14t

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Build wheels
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out ../../dist ${{ env.UNSTABLE_API_FLAGS }}
          sccache: true
          working-directory: packages/protobuf-py-ext

      - name: Build abi3 wheels
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out ../../dist ${{ env.ABI3_FLAGS }}
          sccache: true
          working-directory: packages/protobuf-py-ext

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist

  ext-sdist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build sdist
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          command: sdist
          args: --out ../../dist
          working-directory: packages/protobuf-py-ext

      - name: Upload sdist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-sdist
          path: dist

  release:
    runs-on: ubuntu-24.04
    environment: ${{ (github.event_name == 'workflow_dispatch' && 'pypi-test') || (github.event_name == 'push' && github.ref_type == 'tag' && 'pypi-release') || null }}
    needs:
      - ext-linux
      - ext-windows
      - ext-macos
      - ext-sdist
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          merge-multiple: true

      - run: uv sync --frozen

      # We add the dependency before publishing to match the wheels we publish above while not requiring
      # the native extension for all protobuf-py users / developers.
      - name: add dependency on protobuf-py-ext
        run: uv add "protobuf-py-ext==$(uv version --short); platform_python_implementation == 'CPython' and ((platform_system == 'Linux' and (platform_machine == 'x86_64' or platform_machine == 'aarch64')) or (platform_system == 'Darwin' and platform_machine == 'arm64') or (platform_system == 'Windows' and (platform_machine == 'AMD64' or platform_machine == 'ARM64')))"

      - name: build protobuf-py
        run: uv build

      - name: build protoc-gen-py
        run: uv build
        working-directory: packages/protoc-gen-py

      - name: publish all packages
        if: github.event_name != 'pull_request'
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: ${{ github.event_name == 'workflow_dispatch' && 'https://test.pypi.org/legacy/' || null }}
          skip-existing: true
