# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from fleetbench lifecycle.cc by _fleetbench.py. DO NOT EDIT.
#
# Derived from github.com/google/fleetbench
# Copyright 2025 The Fleetbench Authors
# SPDX-License-Identifier: Apache-2.0
#
# Shared by both the google and protobuf implementations: the message classes,
# access functions, and message operations are all resolved on the `Access`
# object passed at construction.
# ruff: noqa: F841
from __future__ import annotations

from copy import deepcopy
from typing import Any

WORKING_SET_SIZE = 10  # C++ kIterations
MAX_VALUE_STRING_SIZE = 1 << 20


class _Holder:
    """One message type's working set: live messages, peers, and buffers."""

    __slots__ = ("message", "other_message", "string")

    def __init__(self, n: int) -> None:
        self.message: list = [None] * n
        self.other_message: list = [None] * n
        self.string: list[bytes] = [b""] * n


class ProtoLifecycle:
    """Port of fleetbench `ProtoLifecycle`, parameterized by implementation."""

    def __init__(self, access: Any, working_set_size: int = WORKING_SET_SIZE) -> None:
        self._a = access
        self.n = working_set_size
        self.s = "a" * MAX_VALUE_STRING_SIZE
        self.b = self.s.encode()  # pre-encoded so bytes fields don't re-encode
        self.holders = [_Holder(working_set_size) for _ in range(20)]

    def _init_messages(self, holder: _Holder, message_cls: type) -> None:
        """Allocate one message type's working set (C++ `InitMessages`)."""
        for i in range(self.n):
            holder.message[i] = message_cls()
            holder.other_message[i] = message_cls()
            holder.string[i] = b""

    def init(self) -> None:
        a, m, s, b = self._a, self.holders, self.s, self.b
        self._init_messages(m[0], a.Message0)
        self._init_messages(m[1], a.Message1)
        self._init_messages(m[2], a.Message2)
        self._init_messages(m[3], a.Message3)
        self._init_messages(m[4], a.Message4)
        self._init_messages(m[5], a.Message5)
        self._init_messages(m[6], a.Message6)
        self._init_messages(m[7], a.Message7)
        self._init_messages(m[8], a.Message8)
        self._init_messages(m[9], a.Message9)
        self._init_messages(m[10], a.Message10)
        self._init_messages(m[11], a.Message11)
        self._init_messages(m[12], a.Message12)
        self._init_messages(m[13], a.Message13)
        self._init_messages(m[14], a.Message14)
        self._init_messages(m[15], a.Message15)
        self._init_messages(m[16], a.Message16)
        self._init_messages(m[17], a.Message17)
        self._init_messages(m[18], a.Message18)
        self._init_messages(m[19], a.Message19)
        for i in range(self.n):
            a.message0_set_1(m[0].other_message[i], s, b)
            a.message1_set_1(m[1].other_message[i], s, b)
            a.message2_set_1(m[2].other_message[i], s, b)
            a.message3_set_1(m[3].other_message[i], s, b)
            a.message4_set_1(m[4].other_message[i], s, b)
            a.message5_set_1(m[5].other_message[i], s, b)
            a.message6_set_1(m[6].other_message[i], s, b)
            a.message7_set_1(m[7].other_message[i], s, b)
            a.message8_set_1(m[8].other_message[i], s, b)
            a.message9_set_1(m[9].other_message[i], s, b)
            a.message10_set_1(m[10].other_message[i], s, b)
            a.message11_set_1(m[11].other_message[i], s, b)
            a.message12_set_1(m[12].other_message[i], s, b)
            a.message13_set_1(m[13].other_message[i], s, b)
            a.message14_set_1(m[14].other_message[i], s, b)
            a.message15_set_1(m[15].other_message[i], s, b)
            a.message16_set_1(m[16].other_message[i], s, b)
            a.message17_set_1(m[17].other_message[i], s, b)
            a.message18_set_1(m[18].other_message[i], s, b)
            a.message19_set_1(m[19].other_message[i], s, b)

    def run(self) -> None:
        a, m, s, b = self._a, self.holders, self.s, self.b
        for i in range(self.n):
            m[15].message[i] = a.Message15()
            m[8].message[i] = a.Message8()
            m[19].message[i] = a.Message19()
            m[12].message[i] = a.Message12()
            m[19].message[i] = a.parse(a.Message19, m[19].string[i])
            m[6].message[i] = a.Message6()
            m[11].message[i] = a.Message11()
            m[0].message[i] = a.Message0()
            m[18].message[i] = a.Message18()
            m[1].message[i] = a.Message1()
            m[14].message[i] = a.Message14()
            m[8].string[i] = a.serialize(m[8].other_message[i])
            m[5].message[i] = a.Message5()
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[15].string[i] = a.serialize(m[15].message[i])
            m[7].message[i] = a.Message7()
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[10].message[i] = a.Message10()
            m[14].string[i] = a.serialize(m[14].other_message[i])
            m[9].message[i] = a.Message9()
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[6].message[i] = a.Message6()
            a.message6_set_2(m[6].message[i], s, b)
            a.message7_set_2(m[7].other_message[i], s, b)
            m[11].other_message[i] = a.Message11()
            a.message11_set_2(m[11].other_message[i], s, b)
            m[3].message[i] = a.Message3()
            m[16].message[i] = a.Message16()
            m[2].message[i] = a.Message2()
            m[9].other_message[i] = a.Message9()
            a.message9_set_2(m[9].other_message[i], s, b)
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[13].message[i] = a.Message13()
            m[7].string[i] = a.serialize(m[7].other_message[i])
            m[16].string[i] = a.serialize(m[16].message[i])
            a.merge(m[7].message[i], m[7].other_message[i])
            m[17].message[i] = a.Message17()
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[0].string[i] = a.serialize(m[0].other_message[i])
            m[4].message[i] = a.Message4()
            a.merge(m[14].message[i], m[14].other_message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[7].message[i] = a.Message7()
            a.message7_set_2(m[7].message[i], s, b)
            m[18].message[i] = a.parse(a.Message18, m[18].string[i])
            m[11].message[i] = a.Message11()
            a.message11_set_2(m[11].message[i], s, b)
            a.message0_set_2(m[0].other_message[i], s, b)
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[14].string[i] = a.serialize(m[14].message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[7].message[i], m[7].other_message[i] = (
                m[7].other_message[i],
                m[7].message[i],
            )
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[4].other_message[i] = a.parse(a.Message4, m[4].string[i])
            m[19].message[i] = a.Message19()
            a.message19_set_2(m[19].message[i], s, b)
            m[16].string[i] = a.serialize(m[16].other_message[i])
            m[0].message[i] = a.Message0()
            a.message0_set_2(m[0].message[i], s, b)
            a.message1_set_2(m[1].other_message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[11].string[i] = a.serialize(m[11].message[i])
            m[4].string[i] = a.serialize(m[4].other_message[i])
            m[17].message[i] = a.Message17()
            a.message17_set_2(m[17].message[i], s, b)
            m[11].message[i] = deepcopy(m[11].other_message[i])
            a.message6_get_1(m[6].message[i])
            a.message19_set_2(m[19].other_message[i], s, b)
            a.message9_set_2(m[9].other_message[i], s, b)
            m[10].other_message[i] = a.parse(a.Message10, m[10].string[i])
            m[3].message[i], m[3].other_message[i] = (
                m[3].other_message[i],
                m[3].message[i],
            )
            a.merge(m[17].message[i], m[17].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            a.message5_set_2(m[5].other_message[i], s, b)
            m[11].message[i] = deepcopy(m[11].other_message[i])
            a.message12_set_2(m[12].message[i], s, b)
            a.message6_set_2(m[6].other_message[i], s, b)
            m[2].other_message[i] = a.Message2()
            a.message2_set_2(m[2].other_message[i], s, b)
            m[8].other_message[i] = a.parse(a.Message8, m[8].string[i])
            a.message7_get_1(m[7].message[i])
            a.message5_set_3(m[5].message[i], s, b)
            m[8].message[i] = a.Message8()
            a.message8_set_2(m[8].message[i], s, b)
            m[12].message[i] = a.Message12()
            a.message12_set_2(m[12].message[i], s, b)
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[15].string[i] = a.serialize(m[15].message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[16].message[i] = a.Message16()
            a.message16_set_2(m[16].message[i], s, b)
            m[0].other_message[i] = a.parse(a.Message0, m[0].string[i])
            a.message7_get_2(m[7].message[i])
            m[18].message[i] = a.Message18()
            a.message18_set_2(m[18].message[i], s, b)
            a.message0_set_3(m[0].message[i], s, b)
            m[0].other_message[i] = a.parse(a.Message0, m[0].string[i])
            m[19].message[i] = a.Message19()
            a.message19_set_2(m[19].message[i], s, b)
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            a.message12_set_3(m[12].message[i], s, b)
            m[6].string[i] = a.serialize(m[6].other_message[i])
            m[6].other_message[i] = a.parse(a.Message6, m[6].string[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[14].string[i] = a.serialize(m[14].other_message[i])
            m[3].string[i] = a.serialize(m[3].message[i])
            a.merge(m[9].message[i], m[9].other_message[i])
            m[6].message[i] = a.parse(a.Message6, m[6].string[i])
            a.message14_set_2(m[14].other_message[i], s, b)
            a.message19_get_1(m[19].message[i])
            a.merge(m[19].message[i], m[19].other_message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            a.message3_set_2(m[3].other_message[i], s, b)
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[2].message[i] = a.Message2()
            a.message2_set_2(m[2].message[i], s, b)
            a.message2_set_2(m[2].message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[6].string[i] = a.serialize(m[6].message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[2].message[i] = a.parse(a.Message2, m[2].string[i])
            m[15].other_message[i] = a.parse(a.Message15, m[15].string[i])
            m[1].other_message[i] = a.parse(a.Message1, m[1].string[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[12].string[i] = a.serialize(m[12].message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[4].other_message[i] = a.parse(a.Message4, m[4].string[i])
            m[14].message[i] = a.parse(a.Message14, m[14].string[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            a.merge(m[19].message[i], m[19].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[18].string[i] = a.serialize(m[18].message[i])
            m[19].message[i] = a.parse(a.Message19, m[19].string[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            a.message12_set_4(m[12].other_message[i], s, b)
            a.merge(m[4].message[i], m[4].other_message[i])
            a.message0_get_1(m[0].message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            a.message18_set_2(m[18].message[i], s, b)
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[10].string[i] = a.serialize(m[10].message[i])
            m[11].other_message[i] = a.parse(a.Message11, m[11].string[i])
            m[10].string[i] = a.serialize(m[10].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[16].other_message[i] = a.Message16()
            a.message16_set_2(m[16].other_message[i], s, b)
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[11].other_message[i] = a.Message11()
            a.message11_set_2(m[11].other_message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[19].other_message[i] = a.Message19()
            a.message19_set_2(m[19].other_message[i], s, b)
            a.message10_set_2(m[10].message[i], s, b)
            m[1].message[i] = deepcopy(m[1].other_message[i])
            a.message0_get_2(m[0].message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[1].message[i] = a.parse(a.Message1, m[1].string[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[6].string[i] = a.serialize(m[6].message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[13].string[i] = a.serialize(m[13].other_message[i])
            m[15].message[i] = a.Message15()
            a.message15_set_2(m[15].message[i], s, b)
            a.message9_get_1(m[9].message[i])
            m[5].message[i] = a.Message5()
            a.message5_set_2(m[5].message[i], s, b)
            m[5].other_message[i] = a.Message5()
            a.message5_set_2(m[5].other_message[i], s, b)
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[7].message[i] = a.Message7()
            a.message7_set_2(m[7].message[i], s, b)
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[7].other_message[i] = a.Message7()
            a.message7_set_2(m[7].other_message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            a.message13_get_1(m[13].message[i])
            a.message16_set_2(m[16].message[i], s, b)
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[17].message[i] = a.parse(a.Message17, m[17].string[i])
            m[11].message[i] = a.Message11()
            a.message11_set_2(m[11].message[i], s, b)
            a.merge(m[0].message[i], m[0].other_message[i])
            m[12].message[i] = a.Message12()
            a.message12_set_2(m[12].message[i], s, b)
            m[19].message[i], m[19].other_message[i] = (
                m[19].other_message[i],
                m[19].message[i],
            )
            a.message18_set_3(m[18].message[i], s, b)
            m[13].message[i] = deepcopy(m[13].other_message[i])
            a.message18_get_1(m[18].message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[2].other_message[i] = a.Message2()
            a.message2_set_2(m[2].other_message[i], s, b)
            a.message11_set_2(m[11].other_message[i], s, b)
            m[4].other_message[i] = a.Message4()
            a.message4_set_2(m[4].other_message[i], s, b)
            a.merge(m[8].message[i], m[8].other_message[i])
            m[9].message[i] = a.parse(a.Message9, m[9].string[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            a.message5_set_4(m[5].other_message[i], s, b)
            a.message1_get_1(m[1].message[i])
            m[5].string[i] = a.serialize(m[5].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[8].message[i], m[8].other_message[i] = (
                m[8].other_message[i],
                m[8].message[i],
            )
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[15].string[i] = a.serialize(m[15].other_message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[2].other_message[i] = a.Message2()
            a.message2_set_2(m[2].other_message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[9].other_message[i] = a.parse(a.Message9, m[9].string[i])
            m[6].string[i] = a.serialize(m[6].message[i])
            a.message9_get_2(m[9].message[i])
            a.message18_get_2(m[18].message[i])
            a.message6_get_2(m[6].message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            a.message15_get_1(m[15].message[i])
            m[6].string[i] = a.serialize(m[6].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            a.merge(m[9].message[i], m[9].other_message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            a.merge(m[9].message[i], m[9].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[14].other_message[i] = a.parse(a.Message14, m[14].string[i])
            m[15].message[i] = a.parse(a.Message15, m[15].string[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[1].string[i] = a.serialize(m[1].other_message[i])
            m[2].other_message[i] = a.Message2()
            a.message2_set_2(m[2].other_message[i], s, b)
            a.message6_get_3(m[6].message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[14].string[i] = a.serialize(m[14].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            a.message16_set_3(m[16].other_message[i], s, b)
            m[4].other_message[i] = a.Message4()
            a.message4_set_2(m[4].other_message[i], s, b)
            m[1].string[i] = a.serialize(m[1].message[i])
            m[19].string[i] = a.serialize(m[19].other_message[i])
            m[19].other_message[i] = a.Message19()
            a.message19_set_2(m[19].other_message[i], s, b)
            m[0].other_message[i] = a.Message0()
            a.message0_set_2(m[0].other_message[i], s, b)
            a.message16_get_1(m[16].message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[16].message[i] = a.Message16()
            a.message16_set_2(m[16].message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[7].message[i] = a.Message7()
            a.message7_set_2(m[7].message[i], s, b)
            a.message6_get_4(m[6].message[i])
            a.message15_set_2(m[15].message[i], s, b)
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[1].message[i] = a.Message1()
            a.message1_set_2(m[1].message[i], s, b)
            m[11].other_message[i] = a.Message11()
            a.message11_set_2(m[11].other_message[i], s, b)
            m[17].message[i] = a.Message17()
            a.message17_set_2(m[17].message[i], s, b)
            m[2].string[i] = a.serialize(m[2].message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[14].message[i], m[14].other_message[i] = (
                m[14].other_message[i],
                m[14].message[i],
            )
            m[11].message[i] = deepcopy(m[11].other_message[i])
            a.message0_get_3(m[0].message[i])
            a.message11_set_3(m[11].other_message[i], s, b)
            m[15].message[i] = a.Message15()
            a.message15_set_2(m[15].message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[15].other_message[i] = a.Message15()
            a.message15_set_2(m[15].other_message[i], s, b)
            a.message2_set_3(m[2].other_message[i], s, b)
            m[15].other_message[i] = a.Message15()
            a.message15_set_2(m[15].other_message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[1].message[i] = a.parse(a.Message1, m[1].string[i])
            a.merge(m[16].message[i], m[16].other_message[i])
            a.merge(m[19].message[i], m[19].other_message[i])
            m[2].string[i] = a.serialize(m[2].message[i])
            m[6].message[i], m[6].other_message[i] = (
                m[6].other_message[i],
                m[6].message[i],
            )
            a.message9_set_3(m[9].message[i], s, b)
            a.message8_get_1(m[8].message[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[14].string[i] = a.serialize(m[14].other_message[i])
            m[9].other_message[i] = a.Message9()
            a.message9_set_2(m[9].other_message[i], s, b)
            m[1].message[i] = deepcopy(m[1].other_message[i])
            m[13].message[i] = a.Message13()
            a.message13_set_2(m[13].message[i], s, b)
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[18].other_message[i] = a.parse(a.Message18, m[18].string[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[4].other_message[i] = a.parse(a.Message4, m[4].string[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[3].message[i] = a.parse(a.Message3, m[3].string[i])
            a.message13_get_2(m[13].message[i])
            m[11].message[i] = a.Message11()
            a.message11_set_2(m[11].message[i], s, b)
            a.message13_get_3(m[13].message[i])
            m[18].other_message[i] = a.Message18()
            a.message18_set_2(m[18].other_message[i], s, b)
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[1].message[i] = a.Message1()
            a.message1_set_2(m[1].message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[5].other_message[i] = a.Message5()
            a.message5_set_2(m[5].other_message[i], s, b)
            m[5].other_message[i] = a.Message5()
            a.message5_set_2(m[5].other_message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[11].other_message[i] = a.Message11()
            a.message11_set_2(m[11].other_message[i], s, b)
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[6].message[i], m[6].other_message[i] = (
                m[6].other_message[i],
                m[6].message[i],
            )
            m[7].other_message[i] = a.Message7()
            a.message7_set_2(m[7].other_message[i], s, b)
            m[3].message[i] = a.Message3()
            a.message3_set_2(m[3].message[i], s, b)
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[0].string[i] = a.serialize(m[0].message[i])
            m[8].message[i] = a.Message8()
            a.message8_set_2(m[8].message[i], s, b)
            m[16].message[i] = a.parse(a.Message16, m[16].string[i])
            a.message1_set_3(m[1].other_message[i], s, b)
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[2].other_message[i] = a.Message2()
            a.message2_set_2(m[2].other_message[i], s, b)
            m[15].other_message[i] = a.parse(a.Message15, m[15].string[i])
            m[15].other_message[i] = a.Message15()
            a.message15_set_2(m[15].other_message[i], s, b)
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[9].other_message[i] = a.Message9()
            a.message9_set_2(m[9].other_message[i], s, b)
            a.message7_set_3(m[7].other_message[i], s, b)
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[13].other_message[i] = a.Message13()
            a.message13_set_2(m[13].other_message[i], s, b)
            a.message5_get_1(m[5].message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[1].message[i] = a.parse(a.Message1, m[1].string[i])
            m[14].other_message[i] = a.parse(a.Message14, m[14].string[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            a.message2_set_4(m[2].other_message[i], s, b)
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message8_get_2(m[8].message[i])
            a.message12_set_1(m[12].other_message[i], s, b)
            m[19].message[i] = deepcopy(m[19].other_message[i])
            a.message1_get_2(m[1].message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            a.message9_get_3(m[9].message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message15_get_2(m[15].message[i])
            m[18].string[i] = a.serialize(m[18].message[i])
            a.merge(m[1].message[i], m[1].other_message[i])
            m[1].string[i] = a.serialize(m[1].other_message[i])
            m[14].other_message[i] = a.Message14()
            a.message14_set_2(m[14].other_message[i], s, b)
            m[13].message[i] = a.Message13()
            a.message13_set_2(m[13].message[i], s, b)
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            a.message5_get_2(m[5].message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[1].string[i] = a.serialize(m[1].message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[16].message[i] = a.Message16()
            a.message16_set_2(m[16].message[i], s, b)
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[4].message[i] = a.Message4()
            a.message4_set_2(m[4].message[i], s, b)
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[12].other_message[i] = a.Message12()
            a.message12_set_2(m[12].other_message[i], s, b)
            m[3].message[i] = deepcopy(m[3].other_message[i])
            a.message16_get_2(m[16].message[i])
            m[7].message[i] = a.Message7()
            a.message7_set_2(m[7].message[i], s, b)
            m[5].message[i], m[5].other_message[i] = (
                m[5].other_message[i],
                m[5].message[i],
            )
            m[4].message[i] = deepcopy(m[4].other_message[i])
            a.message11_get_1(m[11].message[i])
            m[1].string[i] = a.serialize(m[1].other_message[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            a.message15_get_3(m[15].message[i])
            m[3].string[i] = a.serialize(m[3].other_message[i])
            m[14].string[i] = a.serialize(m[14].message[i])
            a.message15_get_4(m[15].message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[9].other_message[i] = a.Message9()
            a.message9_set_2(m[9].other_message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[4].message[i] = a.parse(a.Message4, m[4].string[i])
            a.message10_set_3(m[10].message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            a.message17_set_2(m[17].other_message[i], s, b)
            a.message18_set_4(m[18].other_message[i], s, b)
            m[12].other_message[i] = a.parse(a.Message12, m[12].string[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[4].string[i] = a.serialize(m[4].other_message[i])
            m[6].message[i] = a.parse(a.Message6, m[6].string[i])
            m[9].string[i] = a.serialize(m[9].message[i])
            m[14].other_message[i] = a.Message14()
            a.message14_set_2(m[14].other_message[i], s, b)
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            a.message11_set_4(m[11].message[i], s, b)
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[6].string[i] = a.serialize(m[6].other_message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[9].string[i] = a.serialize(m[9].message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            a.merge(m[17].message[i], m[17].other_message[i])
            a.message3_set_3(m[3].message[i], s, b)
            m[17].message[i] = a.Message17()
            a.message17_set_2(m[17].message[i], s, b)
            m[19].message[i] = a.parse(a.Message19, m[19].string[i])
            a.message1_get_3(m[1].message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[16].other_message[i] = a.parse(a.Message16, m[16].string[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[15].message[i], m[15].other_message[i] = (
                m[15].other_message[i],
                m[15].message[i],
            )
            m[1].message[i], m[1].other_message[i] = (
                m[1].other_message[i],
                m[1].message[i],
            )
            m[15].string[i] = a.serialize(m[15].message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            a.message19_set_3(m[19].other_message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[1].other_message[i] = a.Message1()
            a.message1_set_2(m[1].other_message[i], s, b)
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[7].other_message[i] = a.parse(a.Message7, m[7].string[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message2_get_1(m[2].message[i])
            m[15].string[i] = a.serialize(m[15].message[i])
            m[7].message[i], m[7].other_message[i] = (
                m[7].other_message[i],
                m[7].message[i],
            )
            m[17].other_message[i] = a.Message17()
            a.message17_set_2(m[17].other_message[i], s, b)
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[5].string[i] = a.serialize(m[5].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[12].other_message[i] = a.Message12()
            a.message12_set_2(m[12].other_message[i], s, b)
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[13].string[i] = a.serialize(m[13].message[i])
            m[13].other_message[i] = a.Message13()
            a.message13_set_2(m[13].other_message[i], s, b)
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[4].other_message[i] = a.Message4()
            a.message4_set_2(m[4].other_message[i], s, b)
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[2].message[i] = a.Message2()
            a.message2_set_2(m[2].message[i], s, b)
            a.message6_set_3(m[6].other_message[i], s, b)
            m[12].other_message[i] = a.parse(a.Message12, m[12].string[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            a.merge(m[7].message[i], m[7].other_message[i])
            m[19].other_message[i] = a.Message19()
            a.message19_set_2(m[19].other_message[i], s, b)
            a.message17_get_1(m[17].message[i])
            m[18].other_message[i] = a.Message18()
            a.message18_set_2(m[18].other_message[i], s, b)
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[0].message[i] = a.Message0()
            a.message0_set_2(m[0].message[i], s, b)
            m[17].message[i] = a.parse(a.Message17, m[17].string[i])
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            a.message10_set_4(m[10].message[i], s, b)
            m[6].message[i] = deepcopy(m[6].other_message[i])
            a.message17_get_2(m[17].message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            a.message15_get_1(m[15].message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            a.message17_set_3(m[17].message[i], s, b)
            m[11].message[i] = a.parse(a.Message11, m[11].string[i])
            m[15].message[i] = a.parse(a.Message15, m[15].string[i])
            m[1].string[i] = a.serialize(m[1].message[i])
            a.message16_get_3(m[16].message[i])
            m[16].message[i] = a.Message16()
            a.message16_set_2(m[16].message[i], s, b)
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            a.merge(m[4].message[i], m[4].other_message[i])
            m[8].other_message[i] = a.Message8()
            a.message8_set_2(m[8].other_message[i], s, b)
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[17].message[i] = a.Message17()
            a.message17_set_2(m[17].message[i], s, b)
            a.message6_get_1(m[6].message[i])
            m[0].string[i] = a.serialize(m[0].message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[7].string[i] = a.serialize(m[7].other_message[i])
            a.message5_get_3(m[5].message[i])
            m[19].other_message[i] = a.parse(a.Message19, m[19].string[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[12].other_message[i] = a.parse(a.Message12, m[12].string[i])
            a.message2_get_2(m[2].message[i])
            a.message7_set_4(m[7].message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[9].other_message[i] = a.Message9()
            a.message9_set_2(m[9].other_message[i], s, b)
            m[15].other_message[i] = a.parse(a.Message15, m[15].string[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[11].string[i] = a.serialize(m[11].message[i])
            a.message6_set_4(m[6].message[i], s, b)
            a.message0_get_4(m[0].message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message17_get_3(m[17].message[i])
            m[18].other_message[i] = a.parse(a.Message18, m[18].string[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[6].string[i] = a.serialize(m[6].other_message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[18].string[i] = a.serialize(m[18].message[i])
            m[17].message[i] = a.parse(a.Message17, m[17].string[i])
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[11].message[i] = deepcopy(m[11].other_message[i])
            m[10].message[i] = a.Message10()
            a.message10_set_2(m[10].message[i], s, b)
            a.merge(m[11].message[i], m[11].other_message[i])
            m[5].message[i] = a.Message5()
            a.message5_set_2(m[5].message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[11].other_message[i] = a.Message11()
            a.message11_set_2(m[11].other_message[i], s, b)
            m[18].message[i] = deepcopy(m[18].other_message[i])
            a.message9_set_4(m[9].other_message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[6].message[i] = a.Message6()
            a.message6_set_2(m[6].message[i], s, b)
            a.message9_set_1(m[9].message[i], s, b)
            a.message17_set_4(m[17].message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[16].other_message[i] = a.Message16()
            a.message16_set_2(m[16].other_message[i], s, b)
            m[15].message[i] = deepcopy(m[15].other_message[i])
            m[13].message[i] = a.Message13()
            a.message13_set_2(m[13].message[i], s, b)
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[0].string[i] = a.serialize(m[0].other_message[i])
            a.message11_set_1(m[11].message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[19].string[i] = a.serialize(m[19].message[i])
            m[13].other_message[i] = a.parse(a.Message13, m[13].string[i])
            a.message4_get_1(m[4].message[i])
            m[19].other_message[i] = a.parse(a.Message19, m[19].string[i])
            m[4].other_message[i] = a.parse(a.Message4, m[4].string[i])
            m[14].string[i] = a.serialize(m[14].message[i])
            m[10].message[i] = a.Message10()
            a.message10_set_2(m[10].message[i], s, b)
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[2].message[i] = a.Message2()
            a.message2_set_2(m[2].message[i], s, b)
            a.message0_set_4(m[0].other_message[i], s, b)
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message18_get_3(m[18].message[i])
            m[8].other_message[i] = a.parse(a.Message8, m[8].string[i])
            m[15].message[i] = a.parse(a.Message15, m[15].string[i])
            m[13].other_message[i] = a.Message13()
            a.message13_set_2(m[13].other_message[i], s, b)
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[18].other_message[i] = a.parse(a.Message18, m[18].string[i])
            m[16].other_message[i] = a.Message16()
            a.message16_set_2(m[16].other_message[i], s, b)
            a.message4_get_2(m[4].message[i])
            m[16].message[i] = deepcopy(m[16].other_message[i])
            m[4].other_message[i] = a.parse(a.Message4, m[4].string[i])
            a.message12_get_1(m[12].message[i])
            m[15].message[i] = deepcopy(m[15].other_message[i])
            a.message7_get_3(m[7].message[i])
            m[13].message[i], m[13].other_message[i] = (
                m[13].other_message[i],
                m[13].message[i],
            )
            m[1].message[i] = a.Message1()
            a.message1_set_2(m[1].message[i], s, b)
            m[18].string[i] = a.serialize(m[18].other_message[i])
            m[7].other_message[i] = a.Message7()
            a.message7_set_2(m[7].other_message[i], s, b)
            m[19].message[i] = a.Message19()
            a.message19_set_2(m[19].message[i], s, b)
            m[9].other_message[i] = a.Message9()
            a.message9_set_2(m[9].other_message[i], s, b)
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[17].string[i] = a.serialize(m[17].other_message[i])
            m[5].other_message[i] = a.parse(a.Message5, m[5].string[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[12].message[i] = a.parse(a.Message12, m[12].string[i])
            a.message16_set_4(m[16].other_message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[2].message[i] = a.parse(a.Message2, m[2].string[i])
            m[19].other_message[i] = a.Message19()
            a.message19_set_2(m[19].other_message[i], s, b)
            m[11].string[i] = a.serialize(m[11].message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[6].message[i] = a.parse(a.Message6, m[6].string[i])
            m[1].message[i], m[1].other_message[i] = (
                m[1].other_message[i],
                m[1].message[i],
            )
            a.message5_set_1(m[5].other_message[i], s, b)
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[7].string[i] = a.serialize(m[7].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[9].message[i] = a.Message9()
            a.message9_set_2(m[9].message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[2].message[i] = a.Message2()
            a.message2_set_2(m[2].message[i], s, b)
            a.message16_get_4(m[16].message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message18_get_4(m[18].message[i])
            m[13].message[i] = deepcopy(m[13].other_message[i])
            m[16].message[i] = a.parse(a.Message16, m[16].string[i])
            m[11].message[i], m[11].other_message[i] = (
                m[11].other_message[i],
                m[11].message[i],
            )
            m[0].message[i], m[0].other_message[i] = (
                m[0].other_message[i],
                m[0].message[i],
            )
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[17].other_message[i] = a.parse(a.Message17, m[17].string[i])
            a.message18_get_1(m[18].message[i])
            m[14].other_message[i] = a.Message14()
            a.message14_set_2(m[14].other_message[i], s, b)
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            a.message18_set_1(m[18].other_message[i], s, b)
            a.message0_set_1(m[0].message[i], s, b)
            m[9].message[i] = deepcopy(m[9].other_message[i])
            a.merge(m[6].message[i], m[6].other_message[i])
            m[10].message[i] = a.Message10()
            a.message10_set_2(m[10].message[i], s, b)
            m[4].message[i] = a.Message4()
            a.message4_set_2(m[4].message[i], s, b)
            m[12].other_message[i] = a.Message12()
            a.message12_set_2(m[12].other_message[i], s, b)
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[1].message[i] = a.parse(a.Message1, m[1].string[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[7].other_message[i] = a.Message7()
            a.message7_set_2(m[7].other_message[i], s, b)
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[6].message[i] = deepcopy(m[6].other_message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            a.merge(m[6].message[i], m[6].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            m[14].other_message[i] = a.Message14()
            a.message14_set_2(m[14].other_message[i], s, b)
            m[18].message[i] = a.parse(a.Message18, m[18].string[i])
            m[9].message[i] = a.Message9()
            a.message9_set_2(m[9].message[i], s, b)
            m[6].other_message[i] = a.parse(a.Message6, m[6].string[i])
            m[8].message[i] = a.Message8()
            a.message8_set_2(m[8].message[i], s, b)
            m[10].message[i] = a.parse(a.Message10, m[10].string[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            a.message9_get_4(m[9].message[i])
            a.message8_set_2(m[8].other_message[i], s, b)
            m[14].message[i] = deepcopy(m[14].other_message[i])
            a.merge(m[14].message[i], m[14].other_message[i])
            a.message13_set_2(m[13].other_message[i], s, b)
            m[10].string[i] = a.serialize(m[10].other_message[i])
            a.message17_get_4(m[17].message[i])
            m[1].other_message[i] = a.Message1()
            a.message1_set_2(m[1].other_message[i], s, b)
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            a.merge(m[16].message[i], m[16].other_message[i])
            m[9].string[i] = a.serialize(m[9].other_message[i])
            m[10].message[i] = a.parse(a.Message10, m[10].string[i])
            m[3].string[i] = a.serialize(m[3].message[i])
            m[16].message[i] = a.Message16()
            a.message16_set_2(m[16].message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            a.message17_set_1(m[17].other_message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[7].message[i] = deepcopy(m[7].other_message[i])
            a.message0_get_1(m[0].message[i])
            m[6].message[i], m[6].other_message[i] = (
                m[6].other_message[i],
                m[6].message[i],
            )
            m[6].message[i] = a.Message6()
            a.message6_set_2(m[6].message[i], s, b)
            m[16].string[i] = a.serialize(m[16].other_message[i])
            m[12].other_message[i] = a.Message12()
            a.message12_set_2(m[12].other_message[i], s, b)
            m[5].message[i] = a.Message5()
            a.message5_set_2(m[5].message[i], s, b)
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[18].message[i] = a.Message18()
            a.message18_set_2(m[18].message[i], s, b)
            m[9].message[i] = a.Message9()
            a.message9_set_2(m[9].message[i], s, b)
            m[16].string[i] = a.serialize(m[16].message[i])
            a.message16_set_1(m[16].other_message[i], s, b)
            m[3].message[i] = a.Message3()
            a.message3_set_2(m[3].message[i], s, b)
            m[10].other_message[i] = a.Message10()
            a.message10_set_2(m[10].other_message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[18].message[i], m[18].other_message[i] = (
                m[18].other_message[i],
                m[18].message[i],
            )
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[5].other_message[i] = a.Message5()
            a.message5_set_2(m[5].other_message[i], s, b)
            m[5].other_message[i] = a.parse(a.Message5, m[5].string[i])
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[17].string[i] = a.serialize(m[17].other_message[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            m[6].message[i] = a.parse(a.Message6, m[6].string[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[4].other_message[i] = a.Message4()
            a.message4_set_2(m[4].other_message[i], s, b)
            m[10].message[i], m[10].other_message[i] = (
                m[10].other_message[i],
                m[10].message[i],
            )
            a.message14_get_1(m[14].message[i])
            m[17].string[i] = a.serialize(m[17].message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            a.message4_set_2(m[4].other_message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[6].other_message[i] = a.Message6()
            a.message6_set_2(m[6].other_message[i], s, b)
            m[10].message[i] = deepcopy(m[10].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            a.message9_get_1(m[9].message[i])
            m[9].string[i] = a.serialize(m[9].message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            a.message8_set_3(m[8].message[i], s, b)
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[18].other_message[i] = a.Message18()
            a.message18_set_2(m[18].other_message[i], s, b)
            m[2].message[i] = deepcopy(m[2].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[5].message[i] = a.parse(a.Message5, m[5].string[i])
            m[14].other_message[i] = a.parse(a.Message14, m[14].string[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            a.message6_set_1(m[6].other_message[i], s, b)
            m[10].message[i] = a.parse(a.Message10, m[10].string[i])
            m[1].other_message[i] = a.parse(a.Message1, m[1].string[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[1].string[i] = a.serialize(m[1].message[i])
            m[9].message[i] = deepcopy(m[9].other_message[i])
            m[10].message[i] = a.parse(a.Message10, m[10].string[i])
            m[5].message[i] = a.parse(a.Message5, m[5].string[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[9].message[i], m[9].other_message[i] = (
                m[9].other_message[i],
                m[9].message[i],
            )
            m[0].message[i] = a.Message0()
            a.message0_set_2(m[0].message[i], s, b)
            m[12].message[i] = deepcopy(m[12].other_message[i])
            a.message3_set_4(m[3].message[i], s, b)
            a.merge(m[19].message[i], m[19].other_message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[6].string[i] = a.serialize(m[6].message[i])
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[1].message[i] = a.parse(a.Message1, m[1].string[i])
            a.message19_set_4(m[19].other_message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[19].other_message[i] = a.Message19()
            a.message19_set_2(m[19].other_message[i], s, b)
            m[18].message[i] = a.Message18()
            a.message18_set_2(m[18].message[i], s, b)
            m[12].string[i] = a.serialize(m[12].other_message[i])
            m[10].string[i] = a.serialize(m[10].message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[17].other_message[i] = a.Message17()
            a.message17_set_2(m[17].other_message[i], s, b)
            m[18].message[i] = deepcopy(m[18].other_message[i])
            m[14].message[i] = deepcopy(m[14].other_message[i])
            m[4].message[i] = a.parse(a.Message4, m[4].string[i])
            m[8].message[i] = a.Message8()
            a.message8_set_2(m[8].message[i], s, b)
            a.message10_get_1(m[10].message[i])
            m[14].other_message[i] = a.parse(a.Message14, m[14].string[i])
            a.message10_set_1(m[10].other_message[i], s, b)
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[19].message[i] = deepcopy(m[19].other_message[i])
            a.message2_set_1(m[2].message[i], s, b)
            m[1].string[i] = a.serialize(m[1].other_message[i])
            a.message19_get_2(m[19].message[i])
            m[14].message[i] = a.Message14()
            a.message14_set_2(m[14].message[i], s, b)
            m[17].message[i] = deepcopy(m[17].other_message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[0].string[i] = a.serialize(m[0].other_message[i])
            m[3].string[i] = a.serialize(m[3].message[i])
            m[10].message[i] = a.Message10()
            a.message10_set_2(m[10].message[i], s, b)
            a.merge(m[8].message[i], m[8].other_message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[0].message[i], m[0].other_message[i] = (
                m[0].other_message[i],
                m[0].message[i],
            )
            a.message8_set_4(m[8].message[i], s, b)
            m[19].string[i] = a.serialize(m[19].other_message[i])
            m[5].message[i], m[5].other_message[i] = (
                m[5].other_message[i],
                m[5].message[i],
            )
            m[1].other_message[i] = a.Message1()
            a.message1_set_2(m[1].other_message[i], s, b)
            m[0].message[i] = a.Message0()
            a.message0_set_2(m[0].message[i], s, b)
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            m[5].other_message[i] = a.parse(a.Message5, m[5].string[i])
            m[18].other_message[i] = a.parse(a.Message18, m[18].string[i])
            m[12].message[i] = a.Message12()
            a.message12_set_2(m[12].message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[5].message[i], m[5].other_message[i] = (
                m[5].other_message[i],
                m[5].message[i],
            )
            m[0].message[i] = deepcopy(m[0].other_message[i])
            m[8].message[i] = a.Message8()
            a.message8_set_2(m[8].message[i], s, b)
            a.message3_set_1(m[3].message[i], s, b)
            m[1].message[i], m[1].other_message[i] = (
                m[1].other_message[i],
                m[1].message[i],
            )
            m[14].other_message[i] = a.Message14()
            a.message14_set_2(m[14].other_message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[0].message[i], m[0].other_message[i] = (
                m[0].other_message[i],
                m[0].message[i],
            )
            a.message1_set_4(m[1].message[i], s, b)
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[1].message[i] = deepcopy(m[1].other_message[i])
            m[0].string[i] = a.serialize(m[0].message[i])
            m[8].message[i] = deepcopy(m[8].other_message[i])
            m[4].string[i] = a.serialize(m[4].message[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            a.message1_set_1(m[1].message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[12].other_message[i] = a.Message12()
            a.message12_set_2(m[12].other_message[i], s, b)
            m[4].other_message[i] = a.parse(a.Message4, m[4].string[i])
            m[4].message[i] = a.Message4()
            a.message4_set_2(m[4].message[i], s, b)
            m[3].message[i] = a.parse(a.Message3, m[3].string[i])
            m[5].message[i] = deepcopy(m[5].other_message[i])
            a.merge(m[5].message[i], m[5].other_message[i])
            a.merge(m[5].message[i], m[5].other_message[i])
            a.message12_get_2(m[12].message[i])
            m[3].message[i] = a.Message3()
            a.message3_set_2(m[3].message[i], s, b)
            m[5].message[i] = deepcopy(m[5].other_message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[3].other_message[i] = a.Message3()
            a.message3_set_2(m[3].other_message[i], s, b)
            m[12].message[i] = deepcopy(m[12].other_message[i])
            m[12].message[i] = a.parse(a.Message12, m[12].string[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            a.message4_get_3(m[4].message[i])
            m[4].message[i] = deepcopy(m[4].other_message[i])
            m[3].other_message[i] = a.parse(a.Message3, m[3].string[i])
            a.merge(m[3].message[i], m[3].other_message[i])
            m[4].message[i], m[4].other_message[i] = (
                m[4].other_message[i],
                m[4].message[i],
            )
            m[4].message[i] = a.parse(a.Message4, m[4].string[i])
            m[3].other_message[i] = a.Message3()
            a.message3_set_2(m[3].other_message[i], s, b)
            m[3].string[i] = a.serialize(m[3].other_message[i])
            m[3].message[i] = a.Message3()
            a.message3_set_2(m[3].message[i], s, b)
            m[3].other_message[i] = a.Message3()
            a.message3_set_2(m[3].other_message[i], s, b)
            a.message3_get_1(m[3].message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[3].message[i] = deepcopy(m[3].other_message[i])
            m[3].message[i] = a.parse(a.Message3, m[3].string[i])
