# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from escaping_proto2.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import TYPE_CHECKING

from protobuf import Enum
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


class EnumStrippedPrefix(Enum):
    """
    ```proto
    enum escaping_proto2.EnumStrippedPrefix
    ```

    Attributes:
        ENUM_STRIPPED_PREFIX_FOO:
            Same as unstripped value, not stripped

            ```proto
            ENUM_STRIPPED_PREFIX_FOO = 0
            ```
        ENUM_STRIPPED_PREFIX_23_B:
            Cannot be stripped - identifier starts with digit

            ```proto
            ENUM_STRIPPED_PREFIX_23_B = 1
            ```
        NOT_STRIPPED_PREFIX:
            Not prefixed

            ```proto
            NOT_STRIPPED_PREFIX = 2
            ```
        FOO_BAR:
            No issues

            ```proto
            ENUM_STRIPPED_PREFIX_FOO_BAR = 3
            ```
        FOO:
            Same as other stripped value

            ```proto
            FOO = 4
            ```
        Foo:
            We don't uppercase so no conflict.

            ```proto
            Foo = 5
            ```
    """

    ENUM_STRIPPED_PREFIX_FOO = 0
    ENUM_STRIPPED_PREFIX_23_B = 1
    NOT_STRIPPED_PREFIX = 2
    FOO_BAR = 3
    FOO = 4
    Foo = 5


_DESC = file_desc(
    b'\n\x15escaping_proto2.proto\x12\x0fescaping_proto2*\x9e\x01\n\x12EnumStrippedPrefix\x12\x1c\n\x18ENUM_STRIPPED_PREFIX_FOO\x10\x00\x12\x1d\n\x19ENUM_STRIPPED_PREFIX_23_B\x10\x01\x12\x17\n\x13NOT_STRIPPED_PREFIX\x10\x02\x12 \n\x1cENUM_STRIPPED_PREFIX_FOO_BAR\x10\x03\x12\x07\n\x03FOO\x10\x04\x12\x07\n\x03Foo\x10\x05',
    [],
    {
        "EnumStrippedPrefix": EnumStrippedPrefix,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `escaping_proto2.proto`."""
    return _DESC
